# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal

logout:
    pattern:   /logout

flock_main:
   resource: "@FlockMainBundle/Resources/config/routing.yml"
