security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    providers:
        fos_userbundle:
            id: fos_user.user_manager
#        flock_twitter_provider:
#            id: flock.twitter.user #Custom user provider with FOSUserBundle as UserManager

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        main:
            pattern:    ^/
            logout: ~
            anonymous: ~

    access_control:
        - { path: ^/event/create , roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/login , roles: IS_AUTHENTICATED_FULLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
