security:

    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    providers:
        fos_twitter:
            id: fos_twitter.auth

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        main:
            pattern:    ^/
            fos_twitter:
                login_path: /login
                check_path: /login_check
                use_twitter_anywhere: true
                always_use_default_target_path: true
                default_target_path: /secured
            logout: ~
            anonymous: ~

    access_control:
        - { path: /login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
