security:
    factories:
        - "%kernel.root_dir%/../vendor/bundles/FOS/TwitterBundle/Resources/config/security_factories.xml"

    providers:
        fos_twitter:
            id: flock_twitter.user_provider #Custom user provider with FOSTwitter and FOSUserBundle as UserManager
    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        main:
            pattern: ^/
            fos_twitter:
                provider: fos_twitter
            anonymous: true
            logout: ~

    access_control:
        - { path: ^/auth/twitter , roles: ROLE_TWITTER }
        - { path: ^/create , roles: ROLE_TWITTER }
        - { path: ^/\d+/toggleJoin , roles: ROLE_TWITTER }
        - { path: ^/\d+/w+ , roles: ROLE_TWITTER }
        - { path: ^/myFlocks , roles: ROLE_TWITTER }
        - { path: ^/login , roles: IS_AUTHENTICATED_ANONYMOUSLY }
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
