flock_auth:
    resource: "@FlockMainBundle/Controller/AuthController.php"
    type:     annotation

flock_default:
    resource: "@FlockMainBundle/Controller/DefaultController.php"
    type:     annotation

flock:
    resource: "@FlockMainBundle/Controller/FlockController.php"
    type:     annotation
