flock_default:
    resource: "@FlockMainBundle/Controller/DefaultController.php"
    type:     annotation

flock_event:
    resource: "@FlockMainBundle/Controller/EventController.php"
    type:     annotation

flock_secured:
    resource: "@FlockMainBundle/Controller/SecuredController.php"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
